### ISSUE TITLE
Suggestion: add Edge extension

### ISSUE THREAD

**Issue by thdoan** [redvanworkshop/sfcc-devtools#13]
Please add an extension for the new Edge browser as well. You should be able to port the Chrome version to Edge without a single code change 99% of the time.

https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension

**Comment by manifestinteractive** [comment]
This has been submitted and pending approval at the following URL ( ETA mid August 2022 at latest for approval ):

https://microsoftedge.microsoft.com/addons/detail/sfcc-devtools/ngabmfehfcfkmiffgfigmfhghfgognle
