### ISSUE TITLE
"Open in business manager" doesn't appear when selecting Content ID comments

### ISSUE THREAD

**Issue by nathanhemesath** [redvanworkshop/sfcc-devtools#2]
#### Overview:
When selecting the Content ID comment, the SFCC window only shows the header "Content Slot", without the button to link to business manager.

#### Steps to Duplicate:
Open inspector and select the dwContentID comment.

#### System Info:
MacOS version: 10.15.3
Chrome version: 79.0.3945.130

**Comment by manifestinteractive** [comment]
@nathanhemesath any chance you can past the comment block you selected as a markdown comment to this thread?  Seems like it's possible that the parsing of the comment is failing, and if that is happening, it is because there is something different about that specific comment block.  Having the actual comment would show me whats going on pretty much immediately.

**Comment by nathanhemesath** [comment]
@manifestinteractive here's the markdown comment.
`<!-- dwMarker="slot" dwContentID="cat-grid-group-1" dwContext="category" dwContextID="400503"-->`

**Comment by nathanhemesath** [comment]
@manifestinteractive ,
I apologize, I didn't realize my initial comment with the markdown was hidden.

**Comment by nathanhemesath** [comment]
@manifestinteractive,
After speaking with someone on your team, I realized the issue is on our end and not with the extension. 
Our code isn't pulling in the SlotUUID, the linking doesn't work with having just the dwContextID.

**Comment by manifestinteractive** [comment]
@nathanhemesath Glad you got that sorted, I was actually having a hard time duplicating this... though maybe I was missing a possible custom setup or something.

BTW, I just found out through Eric that you are with one of our RVW Clients !!!  Stoked to know this is getting used on your team.  I develop this stuff in my free time, so it means a lot to see them used in the wild ❤️
